name: Build & Push Dev Image

on:
  release:
    types: [published]

jobs:
  update:
    uses: codeshelldev/gh-actions/.github/workflows/docker-image.yaml@main
    with:
      registry: ghcr.io
      flavor: |
        latest=false
      tags: |
        type=sha
        type=raw,value=latest-dev
    secrets:
      GH_PCKG_TOKEN: ${{ secrets.GH_PCKG_TOKEN }}
